version: '1.0'

services:
  kong:
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"

  usuario-api-1:
    image: estudo-kong-api-1
    container_name: usuario-api-1
    ports:
      - "5001:80"
    networks:
      - estudo-kong-network

  usuario-api-2:
    image: estudo-kong-api-2
    container_name: usuario-api-2
    ports:
      - "5002:8080"
    networks:
      - estudo-kong-network

  usuario-api-3:
    image: estudo-kong-api-3
    container_name: usuario-api-3
    ports:
      - "5003:8080"
    networks:
      - estudo-kong-network

networks:
  estudo-kong-network: